-- DROP TABLE IF EXISTS module_files;
-- DROP TABLE IF EXISTS submissions;
-- DROP TABLE IF EXISTS submission_sessions;
-- DROP TABLE IF EXISTS assignments;
-- DROP TABLE IF EXISTS learner_modules;
-- DROP TABLE IF EXISTS modules;
-- DROP TABLE IF EXISTS categories;
-- DROP TABLE IF EXISTS learners;
-- DROP TABLE IF EXISTS learnerships;
-- DROP TABLE IF EXISTS lecturers;
-- DROP TABLE IF EXISTS admins;

-- Sequence tracking table for learner_code generation
CREATE TABLE IF NOT EXISTS learner_code_sequences (
    year_val INT PRIMARY KEY,
    last_seq INT NOT NULL
);

-- 1. Admins Table (Spring Security Admin Accounts)
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 1.5 Learnerships Table
CREATE TABLE IF NOT EXISTS learnerships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    qualification_code VARCHAR(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Learners Table
CREATE TABLE IF NOT EXISTS learners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_code VARCHAR(64) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(150) NULL,
    id_number VARCHAR(30) NULL,
    phone_number VARCHAR(30) NULL,
    cohort VARCHAR(100) NULL,
    learnership_id BIGINT NULL,
    password_hash VARCHAR(255) NULL,
    reset_code VARCHAR(6) NULL,
    reset_code_expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_learner_learnership FOREIGN KEY (learnership_id) REFERENCES learnerships(id) ON DELETE SET NULL
);

-- 2.1 Lecturers Table (Now supports Auth)
CREATE TABLE IF NOT EXISTS lecturers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    username VARCHAR(255) NULL UNIQUE,
    password_hash VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2.1.2 Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_type VARCHAR(50) NOT NULL,
    lecturer_id BIGINT NULL,
    learnership_id BIGINT NULL,
    CONSTRAINT fk_category_lecturer FOREIGN KEY (lecturer_id) REFERENCES lecturers(id) ON DELETE SET NULL,
    CONSTRAINT fk_category_learnership FOREIGN KEY (learnership_id) REFERENCES learnerships(id) ON DELETE CASCADE
);

-- 2.2 Modules Table
CREATE TABLE IF NOT EXISTS modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR(255) NOT NULL,
    module_code VARCHAR(100) NULL,
    category_id BIGINT NULL,
    file_path VARCHAR(500) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_module_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- 2.3 Learner Modules Join Table
CREATE TABLE IF NOT EXISTS learner_modules (
    learner_id BIGINT NOT NULL,
    module_id BIGINT NOT NULL,
    PRIMARY KEY (learner_id, module_id),
    CONSTRAINT fk_lm_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
    CONSTRAINT fk_lm_module FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
);

-- 3. Assignments Table
CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    due_date TIMESTAMP NOT NULL,
    module_id BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_assignment_module FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE SET NULL
);

-- 4. Submission Sessions Table
CREATE TABLE IF NOT EXISTS submission_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name VARCHAR(255) NOT NULL,
    assignment_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    task_file_path VARCHAR(500) NULL,
    task_file_name VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_session_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE
);

-- 5. Submissions Table
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    grade INT NULL,
    feedback TEXT NULL,
    graded_at TIMESTAMP NULL,
    graded_file_path VARCHAR(500) NULL,
    graded_original_filename VARCHAR(255) NULL,
    CONSTRAINT fk_submission_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_session FOREIGN KEY (session_id) REFERENCES submission_sessions(id) ON DELETE CASCADE
);

-- 6. Module Files Table
CREATE TABLE IF NOT EXISTS module_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_module_file_module FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
);

-- 8. Moderators Table
CREATE TABLE IF NOT EXISTS moderators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    username VARCHAR(255) NULL UNIQUE,
    password_hash VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 9. Assessors Table
CREATE TABLE IF NOT EXISTS assessors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    username VARCHAR(255) NULL UNIQUE,
    password_hash VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 7. System Settings Table
CREATE TABLE IF NOT EXISTS system_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL
);

INSERT INTO system_settings (setting_key, setting_value)
SELECT 'REGISTRATION_OPEN', 'true'
WHERE NOT EXISTS (SELECT 1 FROM system_settings WHERE setting_key = 'REGISTRATION_OPEN');

-- 10. Audit Log Table (tracks who did what destructive action, and when)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_role VARCHAR(50) NULL,
    actor_username VARCHAR(255) NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NULL,
    details TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Data-loss hardening (2026-08-18): soft-delete for submissions/sessions instead of hard DELETE,
-- and stop assignment deletion from silently cascading away sessions/submissions.
ALTER TABLE submission_sessions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

-- Attribute outcomes to the role/person that recorded them (2026-08-18)
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_by_role VARCHAR(20) NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS graded_by_name VARCHAR(255) NULL;

-- Numeric mark + a flattened, annotated copy of the document (2026-08-19)
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS marks_awarded INTEGER NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS marked_file_path VARCHAR(500) NULL;

ALTER TABLE submission_sessions DROP CONSTRAINT IF EXISTS fk_session_assignment;
ALTER TABLE submission_sessions ADD CONSTRAINT fk_session_assignment
    FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE RESTRICT;

-- 11. Messages Table (one thread per learner/lecturer pair)
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id BIGINT NOT NULL,
    lecturer_id BIGINT NOT NULL,
    sender_type VARCHAR(20) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL,
    CONSTRAINT fk_message_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_lecturer FOREIGN KEY (lecturer_id) REFERENCES lecturers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(learner_id, lecturer_id, created_at);

-- 12. Learner Sessions Table (bearer tokens for the student portal)
-- Only the SHA-256 digest of a token is stored, so a database copy cannot be replayed
-- as a live session. Logout and password reset stamp revoked_at rather than deleting.
CREATE TABLE IF NOT EXISTS learner_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    learner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    CONSTRAINT fk_learner_session_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_learner_sessions_token_hash ON learner_sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_learner_sessions_learner ON learner_sessions(learner_id);

-- 13. Assessor and moderator assignments (Phase 1)
-- An assessor or moderator with no rows here reaches nothing. That is deliberate: before
-- these tables existed, hasRole("ASSESSOR") granted the whole cohort, and an account with no
-- assignments is what every account looks like on the day it is created.
CREATE TABLE IF NOT EXISTS assessor_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessor_id BIGINT NOT NULL,
    learner_id BIGINT NULL,
    category_id BIGINT NULL,
    assigned_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_assessor_assignment_assessor FOREIGN KEY (assessor_id) REFERENCES assessors(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessor_assignment_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
    CONSTRAINT fk_assessor_assignment_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_assessor_assignment_assessor ON assessor_assignments(assessor_id);
CREATE INDEX IF NOT EXISTS idx_assessor_assignment_learner ON assessor_assignments(learner_id);
CREATE INDEX IF NOT EXISTS idx_assessor_assignment_category ON assessor_assignments(category_id);

CREATE TABLE IF NOT EXISTS moderator_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moderator_id BIGINT NOT NULL,
    learnership_id BIGINT NOT NULL,
    cohort VARCHAR(100) NULL,
    scope VARCHAR(20) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_moderator_assignment_moderator FOREIGN KEY (moderator_id) REFERENCES moderators(id) ON DELETE CASCADE,
    CONSTRAINT fk_moderator_assignment_learnership FOREIGN KEY (learnership_id) REFERENCES learnerships(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_moderator_assignment_moderator ON moderator_assignments(moderator_id);
CREATE INDEX IF NOT EXISTS idx_moderator_assignment_learnership ON moderator_assignments(learnership_id);

-- 14. Portfolio of Evidence columns (Phase 2)
-- Every column is nullable. They are added to tables that already hold rows, and a NOT NULL
-- column cannot be added to a populated table without a database default — which would fail
-- the boot that ships it. PoeSchemaBackfill fills the existing rows; new rows arrive with
-- values already set. A later phase can tighten these once no nulls remain.
ALTER TABLE module_files ADD COLUMN IF NOT EXISTS poe_section INTEGER NULL;
ALTER TABLE module_files ADD COLUMN IF NOT EXISTS version INTEGER NULL;
ALTER TABLE module_files ADD COLUMN IF NOT EXISTS is_current BOOLEAN NULL;
ALTER TABLE module_files ADD COLUMN IF NOT EXISTS visible_from TIMESTAMP NULL;
ALTER TABLE module_files ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64) NULL;

ALTER TABLE submissions ADD COLUMN IF NOT EXISTS guide_version_id BIGINT NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS feedback_status VARCHAR(20) NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS feedback_visibility VARCHAR(20) NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64) NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS marked_sha256 VARCHAR(64) NULL;

-- 15. Learner document vault (Phase 3)
-- The learner's own paperwork: CV, ID copy, matric certificate, learnership agreement, and
-- anything else they attach. Rows are never overwritten — re-uploading supersedes the previous
-- version and keeps it, so a document that was rejected and resupplied keeps its history.
-- is_current is NOT NULL here, unlike the Phase 2 columns: this table is new, so there are no
-- existing rows to leave null and no reason to permit one.
CREATE TABLE IF NOT EXISTS learner_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id BIGINT NOT NULL,
    document_type VARCHAR(30) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    sha256 VARCHAR(64) NULL,
    version INTEGER NOT NULL,
    is_current BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    review_note VARCHAR(1000) NULL,
    reviewed_at TIMESTAMP NULL,
    reviewed_by VARCHAR(150) NULL,
    uploaded_at TIMESTAMP NOT NULL,
    uploaded_by_role VARCHAR(20) NOT NULL,
    CONSTRAINT fk_learner_document_learner FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_learner_documents_learner ON learner_documents(learner_id);
CREATE INDEX IF NOT EXISTS idx_learner_documents_current ON learner_documents(learner_id, document_type, is_current);

-- 16. export_jobs.status check constraint cleanup
-- export_jobs itself was Hibernate-managed (ddl-auto=update created it straight from the
-- ExportJob entity) -- but at some point a CHECK constraint was added directly against the
-- database, by hand, listing only the status values ExportJobStatus had at the time. It was
-- never updated when EXPIRED was added later, so every attempt to mark a completed job EXPIRED
-- (PoeExportService.expireJobWithMissingFile, the boot-time recovery for a job whose file didn't
-- survive this deployment's ephemeral disk) has been failing that constraint and getting
-- silently swallowed ever since -- logged as "could not mark job N expired on boot", the job
-- left stuck COMPLETED with a download link that 404s.
-- No other enum-backed status column in this schema has a CHECK constraint at all (ExportJob's
-- own @Enumerated(EnumType.STRING) is what actually keeps its column's values in range); this
-- one was the odd one out and the thing that went stale, so it's dropped rather than recreated
-- with today's value list, which would only reset the same clock for whenever a status is next
-- added. Guarded with IF EXISTS on both the table and the constraint, so this is a safe no-op on
-- a brand-new database (see section 17: the CREATE TABLE below never adds this constraint back)
-- as well as on every already-fixed boot after this one.
ALTER TABLE IF EXISTS export_jobs DROP CONSTRAINT IF EXISTS export_jobs_status_check;

-- 17. Bringing the last Hibernate-managed tables and columns under schema.sql (2026-09-20)
-- ddl-auto was `update`, which on every single boot opens a JDBC connection to the database and
-- asks it, table by table and column by column, "does your schema already match my 27 entities?"
-- On a local Postgres that round trip is free; against a real network hop to the production
-- database it is not, and it was the single largest piece of a 150-190 second boot -- long
-- enough that Render's own deploy health check gave up waiting for the port to open before the
-- app finished starting, twice, on one ordinary deploy.
-- export_jobs above, the five tables below, submission_grading_history, and two columns on
-- submissions (annotations_json, published_at) were the only things ddl-auto=update was actually
-- still doing anything for -- every other table and column already has its own statement above,
-- and ddl-auto=update was, for those, just re-confirming what schema.sql had already set up.
-- Writing these out here and turning ddl-auto off (see application.properties) removes that
-- confirmation pass entirely rather than trying to make it faster.
-- Found by diffing two throwaway local databases: one built by ddl-auto=update against every
-- entity (the actual, fully reconciled schema), one built from schema.sql alone -- so this list
-- is exhaustive as of today's entities, not a manual reading of the Java that could have missed
-- one. Column lists, types, constraints and index names below were taken verbatim from the
-- ddl-auto=update database (via pg_dump), not retyped by hand, so this is what production's
-- tables already look like -- which also means IF NOT EXISTS / ADD COLUMN IF NOT EXISTS make
-- every statement here a true no-op against production the first time this runs. A brand-new
-- database is the only place this DDL actually creates or changes anything.
-- Unlike everything above this section, none of this has a ddl-auto safety net behind it any
-- more: a future field added to one of these entities needs a matching ALTER TABLE here, by
-- hand, the same way every other table in this file already works.
CREATE TABLE IF NOT EXISTS export_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by_id BIGINT NOT NULL,
    requested_by_role VARCHAR(20) NOT NULL,
    scope_type VARCHAR(30) NOT NULL,
    scope_ref VARCHAR(500) NOT NULL,
    scope_label VARCHAR(300) NULL,
    status VARCHAR(20) NOT NULL,
    learner_count INTEGER NULL,
    file_count INTEGER NULL,
    result_public_id VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    error VARCHAR(500) NULL,
    CONSTRAINT export_jobs_scope_type_check CHECK (scope_type IN ('LEARNER', 'COHORT', 'LEARNERSHIP', 'SECTION', 'MODERATION_SAMPLE'))
);
CREATE INDEX IF NOT EXISTS idx_export_job_requester ON export_jobs(requested_by_role, requested_by_id);
CREATE INDEX IF NOT EXISTS idx_export_job_status ON export_jobs(status);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_role VARCHAR(20) NOT NULL,
    type VARCHAR(40) NOT NULL,
    ref_type VARCHAR(40) NULL,
    ref_id BIGINT NULL,
    body VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP NULL,
    CONSTRAINT notifications_type_check CHECK (type IN ('FEEDBACK_RELEASED', 'DOCUMENT_REJECTED', 'GUIDE_PUBLISHED'))
);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(user_id, user_role);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id, user_role, read_at);

CREATE TABLE IF NOT EXISTS signature_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signable_type VARCHAR(30) NOT NULL,
    signable_id BIGINT NOT NULL,
    signer_id BIGINT NOT NULL,
    signer_role VARCHAR(20) NOT NULL,
    signed_at TIMESTAMP NOT NULL,
    declaration_text TEXT NOT NULL,
    document_sha256 VARCHAR(64) NOT NULL,
    verification_code VARCHAR(64) NOT NULL,
    specimen_image TEXT NULL,
    stamped_file_path VARCHAR(500) NULL,
    ip_address VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    revoked_at TIMESTAMP NULL,
    revoked_reason VARCHAR(255) NULL,
    CONSTRAINT idx_signature_events_code UNIQUE (verification_code),
    CONSTRAINT signature_events_signable_type_check CHECK (signable_type IN ('SUBMISSION', 'LEARNER_DOCUMENT'))
);
CREATE INDEX IF NOT EXISTS idx_signature_events_signable ON signature_events(signable_type, signable_id);

CREATE TABLE IF NOT EXISTS poe_document_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learnership_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    required BOOLEAN NOT NULL,
    required_from DATE NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_poe_document_requirement_learnership FOREIGN KEY (learnership_id) REFERENCES learnerships(id),
    CONSTRAINT uk_requirement_learnership_type UNIQUE (learnership_id, document_type),
    CONSTRAINT poe_document_requirements_document_type_check CHECK (document_type IN ('CV', 'ID_COPY', 'AGREEMENT', 'MATRIC', 'OTHER'))
);

CREATE TABLE IF NOT EXISTS legacy_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_username VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_zip_path VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL,
    entry_count INTEGER NOT NULL,
    importable_count INTEGER NOT NULL,
    unmatched_count INTEGER NOT NULL,
    imported_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    confirmed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    CONSTRAINT legacy_import_batches_status_check CHECK (status IN ('PREVIEWED', 'CONFIRMED', 'CANCELLED'))
);

-- submissions columns that were also only Hibernate-managed until now (found by diffing a
-- database ddl-auto=update had fully reconciled against one schema.sql alone produced -- see
-- section 17's note above).
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS annotations_json TEXT NULL;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS published_at TIMESTAMP NULL;
CREATE INDEX IF NOT EXISTS idx_submission_learner_session ON submissions(learner_id, session_id);

CREATE TABLE IF NOT EXISTS submission_grading_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    graded_at TIMESTAMP NOT NULL,
    graded_by_role VARCHAR(20) NOT NULL,
    graded_by_name VARCHAR(255) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    marks_awarded INTEGER NULL,
    feedback TEXT NULL,
    feedback_visibility VARCHAR(20) NULL,
    CONSTRAINT fk_submission_grading_history_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT submission_grading_history_outcome_check CHECK (outcome IN ('SUBMITTED', 'LATE', 'COMPETENT', 'NOT_YET_COMPETENT')),
    CONSTRAINT submission_grading_history_feedback_visibility_check CHECK (feedback_visibility IN ('LEARNER', 'INTERNAL'))
);

CREATE TABLE IF NOT EXISTS legacy_import_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    top_folder VARCHAR(255) NULL,
    zip_entry_path VARCHAR(1000) NOT NULL,
    document_type VARCHAR(30) NULL,
    file_size_bytes BIGINT NULL,
    matched_learner_id BIGINT NULL,
    matched_learner_name VARCHAR(255) NULL,
    match_confidence VARCHAR(20) NOT NULL,
    importable BOOLEAN NOT NULL,
    note VARCHAR(500) NULL,
    imported_document_id BIGINT NULL,
    import_error VARCHAR(500) NULL,
    CONSTRAINT fk_legacy_import_entry_batch FOREIGN KEY (batch_id) REFERENCES legacy_import_batches(id),
    CONSTRAINT fk_legacy_import_entry_learner FOREIGN KEY (matched_learner_id) REFERENCES learners(id),
    CONSTRAINT legacy_import_entries_document_type_check CHECK (document_type IN ('CV', 'ID_COPY', 'AGREEMENT', 'MATRIC', 'OTHER')),
    CONSTRAINT legacy_import_entries_match_confidence_check CHECK (match_confidence IN ('EXACT', 'LIKELY', 'UNMATCHED', 'SPECIFIED'))
);
CREATE INDEX IF NOT EXISTS idx_legacy_import_entries_batch ON legacy_import_entries(batch_id);

-- Indexes ddl-auto=update was also still (re-)creating on every boot, on three tables that
-- already have their own CREATE TABLE above -- found the same way as section 17: diffing a
-- ddl-auto=update-reconciled database against a schema.sql-only one and comparing indexes too,
-- not just columns.
CREATE INDEX IF NOT EXISTS idx_learner_modules_learner ON learner_modules(learner_id);
CREATE INDEX IF NOT EXISTS idx_learner_modules_module ON learner_modules(module_id);
CREATE INDEX IF NOT EXISTS idx_message_learner_lecturer_read ON messages(learner_id, lecturer_id, read_at);
CREATE INDEX IF NOT EXISTS idx_session_status_end_time ON submission_sessions(status, end_time);
